{{- if .Values.artifusion.config.github.required_org }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifusion.fullname" . }}-github-packages
  labels:
    {{- include "artifusion.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.github.username | quote }}
  token: {{ .Values.secrets.github.token | quote }}
{{- end }}
